package edu.generalpuzzle.infra;

/**
 * Created by IntelliJ IDEA.
 * Date: 08/06/2008
 */
public class CellId implements Comparable {

    /** id, like 100*X+10*Y+Z <p>
	different calculation per lattice type */
    private int id;

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return Integer.toString(id-1);
    }

    public void setId(int id) {
        this.id = id;
    }

    public CellId(int id) {
        this.id = id;
    }

    public CellId() {
    }

    // generated by intelliJ
    @Override
    public boolean equals(Object o) {
        final CellId cellId = (CellId) o;
        return id == cellId.id;
    }

    @Override
    public int hashCode() {
        return id;
    }

//    @Override - JVM 5 problem with the annotation
    public int compareTo(Object o) {
        CellId other = (CellId)o;
        return getId() - other.getId();
    }

}
