name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Specifies the Node.js version
          cache: 'npm'       # Automatically caches your npm dependencies

      - name: Install dependencies
        run:  |
          cd node-js
          npm ci

      - name: Run tests
        run:  |
          cd node-js
          npm test
